// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza;

#nullable disable

namespace Pizza.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20241211175512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Pizza.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pizza.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pizza with many Ingredients",
                            Ingredients = "[\"Pepperoni\",\"Sausage\",\"Bacon\",\"Ham\",\"Beef\",\"Mushroom\",\"Bell Peppers\",\"Onions\",\"Mushrooms\",\"Olives\",\"Tomato Sauce\"]",
                            Name = "Supreme",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic pizza with pepperoni",
                            Ingredients = "[\"Pepperoni\",\"Mozzarella\",\"Tomato Sauce\"]",
                            Name = "Pepperoni",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Simple and delicious cheese pizza",
                            Ingredients = "[\"Mozzarella\",\"Cheddar\",\"Parmesan\",\"Tomato Sauce\"]",
                            Name = "Cheese",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A healthy pizza loaded with vegetables",
                            Ingredients = "[\"Bell Peppers\",\"Onions\",\"Mushrooms\",\"Olives\",\"Tomato Sauce\"]",
                            Name = "Veggie",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pizza for meat enthusiasts",
                            Ingredients = "[\"Pepperoni\",\"Sausage\",\"Bacon\",\"Ham\",\"Beef\",\"Mozzarella\",\"Tomato Sauce\"]",
                            Name = "Meat Lover",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pizza with your choice of Toppings",
                            Ingredients = "[\"Mozzarella\",\"Tomato Sauce\"]",
                            Name = "Build Your Own",
                            Price = 14.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
